server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

ribbon:  
  ReadTimeout: 10000 
  ConnectTimeout: 10000      
      
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用阿里的Druid连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://47.105.189.247:3306/jyweb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 http://localhost:8083/druid/sql.html
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

# 发送post请求自动刷新配置：http://localhost:8084/actuator/bus-refresh
  #rabbitmq配置
  rabbitmq:
    host: 192.168.36.129
    port: 5672
    username: admin
    password: mypass
  cloud:     
    bus: 
      enabled: true
      trace:
        enabled: true
        
#Mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kang.model.mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
    
# log
logging:
  level:
    root: com.kang.mapper:INFO

#FastDFS配置
fdfs:
  webserver: http://192.168.36.129:8080/
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:     #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.36.129:22122




