server:
  port: 8771
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: springcloud-config-kang
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared




