server:
  port: 8771
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: springcloud-config-kang
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared


  #rabbitmq配置
  rabbitmq:
    host: 192.168.36.130
    port: 5672
    username: admin
    password: mypass
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chao533/springcloud_kang.git     # 配置git仓库的地址
          search-paths: config-repo                                # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号（私有库必填）
          password:                                             # git仓库的密码（私有库必填）
      label: master                                        #配置git仓库的分支
    bus: 
      enabled: true
      trace:
        enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

#访问远程配置文件
# http://localhost:8771/master/springcloud-login-kang-dev.yml
# http://localhost:8771/master/springcloud-base-kang-dev.yml


